### ISSUE TITLE
[regression, bisected] 1.3.3 fails to build on non-VSX ppc64 CPUs

### ISSUE THREAD

**Issue by ernsteiswuerfel** [xiph/flac#199]
`./configure && make` works fine with 1.3.2.

With 1.3.3 I get:
```
make[4]: Entering directory '/root/build/flac/src/libFLAC'
  CC       bitmath.lo
  CC       bitreader.lo
  CC       bitwriter.lo
  CC       cpu.lo
  CC       crc.lo
  CC       fixed.lo
  CC       fixed_intrin_sse2.lo
  CC       fixed_intrin_ssse3.lo
  CC       float.lo
  CC       format.lo
  CC       lpc.lo
  CC       lpc_intrin_sse.lo
  CC       lpc_intrin_sse2.lo
  CC       lpc_intrin_sse41.lo
  CC       lpc_intrin_avx2.lo
  CC       lpc_intrin_vsx.lo
lpc_intrin_vsx.c: In function 'FLAC__lpc_compute_autocorrelation_intrin_power8_vsx_lag_16':
lpc_intrin_vsx.c:94:7: warning: implicit declaration of function 'vec_vsx_ld'; did you mean 'vec_vslh'? [-Wimplicit-function-declaration]
   94 |  d0 = vec_vsx_ld(0, base);
      |       ^~~~~~~~~~
      |       vec_vslh
lpc_intrin_vsx.c:94:7: warning: nested extern declaration of 'vec_vsx_ld' [-Wnested-externs]
lpc_intrin_vsx.c:94:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
lpc_intrin_vsx.c:95:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
   95 |  d1 = vec_vsx_ld(16, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:96:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
   96 |  d2 = vec_vsx_ld(32, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:97:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
   97 |  d3 = vec_vsx_ld(48, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:104:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  104 |   d4 = vec_vsx_ld(0, base);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:158:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  158 |   d0 = vec_vsx_ld(0, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:159:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  159 |   d1 = vec_vsx_ld(16, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:160:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  160 |   d2 = vec_vsx_ld(32, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:161:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  161 |   d3 = vec_vsx_ld(48, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:170:2: warning: implicit declaration of function 'vec_vsx_st'; did you mean 'vec_dstst'? [-Wimplicit-function-declaration]
  170 |  vec_vsx_st(sum0, 0, autoc);
      |  ^~~~~~~~~~
      |  vec_dstst
lpc_intrin_vsx.c:170:2: warning: nested extern declaration of 'vec_vsx_st' [-Wnested-externs]
lpc_intrin_vsx.c:170:2: error: AltiVec argument passed to unprototyped function
lpc_intrin_vsx.c:171:2: error: AltiVec argument passed to unprototyped function
  171 |  vec_vsx_st(sum1, 16, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:172:2: error: AltiVec argument passed to unprototyped function
  172 |  vec_vsx_st(sum2, 32, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:173:2: error: AltiVec argument passed to unprototyped function
  173 |  vec_vsx_st(sum3, 48, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c: In function 'FLAC__lpc_compute_autocorrelation_intrin_power8_vsx_lag_12':
lpc_intrin_vsx.c:225:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  225 |  d0 = vec_vsx_ld(0, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:226:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  226 |  d1 = vec_vsx_ld(16, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:227:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  227 |  d2 = vec_vsx_ld(32, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:234:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  234 |   d3 = vec_vsx_ld(0, base);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:280:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  280 |   d0 = vec_vsx_ld(0, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:281:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  281 |   d1 = vec_vsx_ld(16, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:282:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  282 |   d2 = vec_vsx_ld(32, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:290:2: error: AltiVec argument passed to unprototyped function
  290 |  vec_vsx_st(sum0, 0, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:291:2: error: AltiVec argument passed to unprototyped function
  291 |  vec_vsx_st(sum1, 16, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:292:2: error: AltiVec argument passed to unprototyped function
  292 |  vec_vsx_st(sum2, 32, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c: In function 'FLAC__lpc_compute_autocorrelation_intrin_power8_vsx_lag_8':
lpc_intrin_vsx.c:340:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  340 |  d0 = vec_vsx_ld(0, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:341:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  341 |  d1 = vec_vsx_ld(16, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:348:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  348 |   d2 = vec_vsx_ld(0, base);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:386:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  386 |   d0 = vec_vsx_ld(0, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:387:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  387 |   d1 = vec_vsx_ld(16, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:394:2: error: AltiVec argument passed to unprototyped function
  394 |  vec_vsx_st(sum0, 0, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:395:2: error: AltiVec argument passed to unprototyped function
  395 |  vec_vsx_st(sum1, 16, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c: In function 'FLAC__lpc_compute_autocorrelation_intrin_power8_vsx_lag_4':
lpc_intrin_vsx.c:439:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  439 |  d0 = vec_vsx_ld(0, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:446:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  446 |   d1 = vec_vsx_ld(0, base);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:476:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  476 |   d0 = vec_vsx_ld(0, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:482:2: error: AltiVec argument passed to unprototyped function
  482 |  vec_vsx_st(sum0, 0, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c: In function 'FLAC__lpc_compute_autocorrelation_intrin_power9_vsx_lag_16':
lpc_intrin_vsx.c:540:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  540 |  d0 = vec_vsx_ld(0, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:541:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  541 |  d1 = vec_vsx_ld(16, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:542:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  542 |  d2 = vec_vsx_ld(32, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:543:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  543 |  d3 = vec_vsx_ld(48, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:550:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  550 |   d4 = vec_vsx_ld(0, base);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:604:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  604 |   d0 = vec_vsx_ld(0, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:605:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  605 |   d1 = vec_vsx_ld(16, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:606:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  606 |   d2 = vec_vsx_ld(32, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:607:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  607 |   d3 = vec_vsx_ld(48, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:616:2: error: AltiVec argument passed to unprototyped function
  616 |  vec_vsx_st(sum0, 0, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:617:2: error: AltiVec argument passed to unprototyped function
  617 |  vec_vsx_st(sum1, 16, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:618:2: error: AltiVec argument passed to unprototyped function
  618 |  vec_vsx_st(sum2, 32, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:619:2: error: AltiVec argument passed to unprototyped function
  619 |  vec_vsx_st(sum3, 48, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c: In function 'FLAC__lpc_compute_autocorrelation_intrin_power9_vsx_lag_12':
lpc_intrin_vsx.c:671:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  671 |  d0 = vec_vsx_ld(0, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:672:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  672 |  d1 = vec_vsx_ld(16, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:673:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  673 |  d2 = vec_vsx_ld(32, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:680:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  680 |   d3 = vec_vsx_ld(0, base);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:726:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  726 |   d0 = vec_vsx_ld(0, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:727:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  727 |   d1 = vec_vsx_ld(16, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:728:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  728 |   d2 = vec_vsx_ld(32, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:736:2: error: AltiVec argument passed to unprototyped function
  736 |  vec_vsx_st(sum0, 0, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:737:2: error: AltiVec argument passed to unprototyped function
  737 |  vec_vsx_st(sum1, 16, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:738:2: error: AltiVec argument passed to unprototyped function
  738 |  vec_vsx_st(sum2, 32, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c: In function 'FLAC__lpc_compute_autocorrelation_intrin_power9_vsx_lag_8':
lpc_intrin_vsx.c:786:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  786 |  d0 = vec_vsx_ld(0, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:787:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  787 |  d1 = vec_vsx_ld(16, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:794:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  794 |   d2 = vec_vsx_ld(0, base);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:832:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  832 |   d0 = vec_vsx_ld(0, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:833:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  833 |   d1 = vec_vsx_ld(16, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:840:2: error: AltiVec argument passed to unprototyped function
  840 |  vec_vsx_st(sum0, 0, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c:841:2: error: AltiVec argument passed to unprototyped function
  841 |  vec_vsx_st(sum1, 16, autoc);
      |  ^~~~~~~~~~
lpc_intrin_vsx.c: In function 'FLAC__lpc_compute_autocorrelation_intrin_power9_vsx_lag_4':
lpc_intrin_vsx.c:885:7: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  885 |  d0 = vec_vsx_ld(0, base);
      |       ^~~~~~~~~~
lpc_intrin_vsx.c:892:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  892 |   d1 = vec_vsx_ld(0, base);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:922:8: error: incompatible types when assigning to type '__vector float' {aka '__vector(4) float'} from type 'int'
  922 |   d0 = vec_vsx_ld(0, data+i);
      |        ^~~~~~~~~~
lpc_intrin_vsx.c:928:2: error: AltiVec argument passed to unprototyped function
  928 |  vec_vsx_st(sum0, 0, autoc);
      |  ^~~~~~~~~~
make[4]: *** [Makefile:731: lpc_intrin_vsx.lo] Error 1
make[4]: Leaving directory '/root/build/flac/src/libFLAC'
make[3]: *** [Makefile:793: all-recursive] Error 1
make[3]: Leaving directory '/root/build/flac/src/libFLAC'
make[2]: *** [Makefile:432: all-recursive] Error 1
make[2]: Leaving directory '/root/build/flac/src'
make[1]: *** [Makefile:491: all-recursive] Error 1
make[1]: Leaving directory '/root/build/flac'
make: *** [Makefile:423: all] Error 2
```
Machine is a PowerMac G5 11,2.

```
 # inxi -b
System:    Kernel: 5.6.2-gentoo-PowerMacG5 ppc64 bits: 64 Console: tty 2 Distro: Gentoo Base System release 2.6 
Machine:   Type: PowerPC Device System: PowerMac11 2 details: PowerMac11 2 rev: 1.1 (pvr 0044 0101) serial: R6V 
CPU:       Dual Core: PPC970MP altivec supported type: MCP speed: 2300 MHz min/max: 1150/2300 MHz 
Graphics:  Device-1: NVIDIA NV43 [GeForce 6600] driver: N/A 
           Device-2: Advanced Micro Devices [AMD/ATI] RV530 [Radeon X1600 PRO] driver: radeon v: kernel 
           Display: server: X.org 1.20.7 driver: ati,radeon tty: 211x53 
           Message: Advanced graphics data unavailable in console for root. 
Network:   Device-1: Broadcom and subsidiaries NetXtreme BCM5780 Gigabit Ethernet driver: tg3 
           Device-2: Broadcom and subsidiaries NetXtreme BCM5780 Gigabit Ethernet driver: tg3 
           Device-3: Qualcomm Atheros AR242x / AR542x Wireless Network Adapter driver: ath5k 
Drives:    Local Storage: total: 577.55 GiB used: 4.04 GiB (0.7%) 
Info:      Processes: 125 Uptime: 2h 55m Memory: 15.43 GiB used: 1.21 GiB (7.9%) Init: systemd Shell: bash inxi: 3.0.36 
```

Already posted this bug, but to the wrong place it seems. ;)
https://sourceforge.net/p/flac/bugs/475/

[config.log](https://github.com/xiph/flac/files/4431774/config.log)
[config.h.txt](https://github.com/xiph/flac/files/4431775/config.h.txt)

**Comment by ernsteiswuerfel** [comment]
Bisected the bug.
```
# git bisect good | tee -a ~/bisect01.log
cdb030cd3749b4547399a049ce3cae5e974ccd48 is the first bad commit
commit cdb030cd3749b4547399a049ce3cae5e974ccd48
Author: Anton Blanchard <anton@ozlabs.org>
Date:   Sat Jul 7 14:21:46 2018 +1000

    Add VSX optimised versions of autocorrelation loops
    
    Add a POWER8 and POWER9 version of the autocorrelation functions.
    
    flac --best is about 3.3x faster on POWER9 with this patch.
    
    Signed-off-by: Anton Blanchard <anton@ozlabs.org>

 src/libFLAC/Makefile.am           |   1 +
 src/libFLAC/include/private/lpc.h |  14 +
 src/libFLAC/lpc_intrin_vsx.c      | 942 ++++++++++++++++++++++++++++++++++++++
 src/libFLAC/stream_encoder.c      |  30 ++
 4 files changed, 987 insertions(+)
 create mode 100644 src/libFLAC/lpc_intrin_vsx.c
```
[bisect01.log](https://github.com/xiph/flac/files/4432705/bisect01.log)

**Comment by erikd** [comment]
@antonblanchard any chance of a workaround or patch so this can build on non-VSX ppc64?

**Comment by miniupnp** [comment]
isn't https://github.com/xiph/flac/pull/194 fixing compilation for PPC macs ?
G4 and G5 are VSX, but only version 2.03.

**Comment by miniupnp** [comment]
hum sorry you are using linux.

`vec_vsx_ld` should only be used to accept unaligned data. `vec_ld` should be used if alignment is guaranteed.

**Comment by miniupnp** [comment]
note from gcc doc : 

> Note that the ‘vec_ld’ and ‘vec_st’ built-in functions always generate the AltiVec ‘LVX’ and ‘STVX’ instructions even if the VSX instruction set is available. The ‘vec_vsx_ld’ and ‘vec_vsx_st’ built-in functions always generate the VSX ‘LXVD2X’, ‘LXVW4X’, ‘STXVD2X’, and ‘STXVW4X’ instructions.

**Comment by ktmf01** [comment]
If anyone listening in on this issue has the proper setup (I don't), would it be possible for them to check whether #317 fixes this issue?

**Comment by ernsteiswuerfel** [comment]
Applied your patch on git master. Unfortunately it does not fix the problem yet. But the error messages changed. 😉 
[build.log](https://github.com/xiph/flac/files/8516966/build.log)
[config.log](https://github.com/xiph/flac/files/8516961/config.log)
[config.h.txt](https://github.com/xiph/flac/files/8516965/config.h.txt)

**Comment by ktmf01** [comment]
Are you sure you applied the whole patch? This in particular: https://github.com/xiph/flac/pull/317/commits/d26487eb0935bb3a558ecad1d09dcee7a1fe8619

In your config.log I read this

```
configure:19315: checking for  __attribute__ ((target("cpu=power8")))
configure:19333: gcc -c   conftest.c >&5
configure:19333: $? = 0
configure:19342: result: yes
configure:19358: checking for  __attribute__ ((target("cpu=power9")))
configure:19376: gcc -c   conftest.c >&5
configure:19376: $? = 0
configure:19385: result: yes
configure:19789: checking for doxygen
```

In my config.log (made with a crosscompiler) I find this
```
configure:18218: checking for  __attribute__ ((target("cpu=power8")))
configure:18235: powerpc64le-linux-gnu-gcc -c   conftest.c >&5
configure:18235: $? = 0
configure:18243: result: yes
configure:18258: checking for  __attribute__ ((target("cpu=power9")))
configure:18275: powerpc64le-linux-gnu-gcc -c   conftest.c >&5
configure:18275: $? = 0
configure:18283: result: yes
configure:18298: checking whether altivec.h has vec_doubleh()
configure:18311: powerpc64le-linux-gnu-gcc -c   conftest.c >&5
configure:18311: $? = 0
configure:18312: result: yes
configure:18697: checking for doxygen
```

Seeing the code I just linked, I cannot see how it is possible it didn't check for vec_doubleh(), and passed `if test "x$use_vsx$has_vec_doubleh" = xtruetrue ; then` if it didn't check at all

**Comment by ernsteiswuerfel** [comment]
@ktmf01 Strange, now it works... Don't know what I picked up yesterday, thought it was the whole series.

Anyway, https://github.com/xiph/flac/commit/d26487eb0935bb3a558ecad1d09dcee7a1fe8619 you pointed out fixes the build and also no problems when I apply the whole series at #317. So this issue finally seems to be sorted out. Thanks! 🥳 

This was on my Talos II G5 partition. I'll check out on the G5 natively the next weekend just to be sure.

**Comment by ernsteiswuerfel** [comment]
Now I can confirm current git-master builds fine too on the G5 I originally reported the bug on. Thanks!
